### ISSUE TITLE
 The wrong version of bibtextparser

### ISSUE THREAD

**Issue by XuhuiZhou** [sotopia-lab/awesome-social-agents#15]
@zhenwu0831 
`.loads` seems to be the old way of importing the bibs of the package.

Note that we use the pre-release package.
https://bibtexparser.readthedocs.io/en/main/quickstart.html

_Originally posted by @XuhuiZhou in https://github.com/sotopia-lab/awesome-social-agents/issues/4#issuecomment-2059824965_

**Comment by ProKil** [comment]
Is this a feature request? Bump up version?

**Comment by XuhuiZhou** [comment]
Already fixed by @jennytliang !
